/* Keep generated tailwind.css checked in; Python serves it without Node.js. */
const themeConfig = {
      darkMode: "class",
      theme: {
        extend: {
          "colors": {
            "surface-dim": "#dadad8",
            "surface-container": "#efeeec",
            "surface-container-low": "#f4f3f1",
            "secondary-fixed-dim": "#cbc5c0",
            "secondary-container": "#e5dfd9",
            "on-secondary-container": "#66625e",
            "surface-container-high": "#e9e8e6",
            "on-secondary-fixed": "#1d1b18",
            "inverse-surface": "#2f3130",
            "on-background": "#1a1c1b",
            "surface-container-lowest": "#ffffff",
            "on-secondary-fixed-variant": "#494643",
            "secondary-fixed": "#e7e1dc",
            "on-tertiary-fixed": "#1e1b15",
            "on-primary": "#ffffff",
            "on-surface-variant": "#584239",
            "error-container": "#ffdad6",
            "tertiary-fixed": "#e9e1d7",
            "outline-variant": "#dfc0b5",
            "on-error-container": "#93000a",
            "surface": "#faf9f7",
            "error": "#ba1a1a",
            "on-surface": "#1a1c1b",
            "background": "#faf9f7",
            "surface-container-highest": "#e3e2e0",
            "on-primary-fixed": "#370e00",
            "on-error": "#ffffff",
            "primary-container": "#c45118",
            "secondary": "#615e5a",
            "surface-bright": "#faf9f7",
            "on-tertiary-container": "#fffcff",
            "primary-fixed-dim": "#ffb598",
            "primary-fixed": "#ffdbce",
            "on-tertiary-fixed-variant": "#4a463f",
            "on-primary-fixed-variant": "#7e2c00",
            "tertiary-fixed-dim": "#cdc5bc",
            "on-tertiary": "#ffffff",
            "primary": "#a23b00",
            "inverse-on-surface": "#f1f1ef",
            "surface-tint": "#a53c00",
            "on-primary-container": "#fffcff",
            "outline": "#8b7168",
            "on-secondary": "#ffffff",
            "inverse-primary": "#ffb598",
            "tertiary-container": "#79746c",
            "tertiary": "#605b54",
            "surface-variant": "#e3e2e0"
          },
          "borderRadius": {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem"
          },
          "spacing": {
            "gutter-mobile": "1rem",
            "space-xl": "2.5rem",
            "space-lg": "1.5rem",
            "space-2xl": "4rem",
            "margin-mobile": "1.25rem",
            "margin": "3rem",
            "gutter": "1.5rem",
            "space-md": "1rem",
            "space-sm": "0.5rem",
            "space-xs": "0.25rem"
          },
          "fontFamily": {
            "display-lg": ["Google Sans", "Arial", "sans-serif"],
            "body-sm": ["Google Sans", "Arial", "sans-serif"],
            "headline-lg": ["Google Sans", "Arial", "sans-serif"],
            "display-lg-mobile": ["Google Sans", "Arial", "sans-serif"],
            "headline-sm": ["Google Sans", "Arial", "sans-serif"],
            "headline-lg-mobile": ["Google Sans", "Arial", "sans-serif"],
            "headline-md": ["Google Sans", "Arial", "sans-serif"],
            "label-sm": ["Google Sans", "Arial", "sans-serif"],
            "label-md": ["Google Sans", "Arial", "sans-serif"],
            "title-md": ["Google Sans", "Arial", "sans-serif"],
            "body-lg": ["Google Sans", "Arial", "sans-serif"],
            "body-md": ["Google Sans", "Arial", "sans-serif"]
          },
          "fontSize": {
            "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
            "body-sm": ["13px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "400" }],
            "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
            "display-lg-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
            "headline-sm": ["22px", { "lineHeight": "30px", "letterSpacing": "0em", "fontWeight": "500" }],
            "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "0em", "fontWeight": "600" }],
            "headline-md": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
            "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "600" }],
            "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "600" }],
            "title-md": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
            "body-lg": ["17px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400" }],
            "body-md": ["15px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }]
          }
        },
      },
    };

module.exports = {
  ...themeConfig,
  content: ["./index.html", "./app.js"],
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
